#!/usr/bin/env bash
# ============================================================
# FormForge — Stripe Test → Live Mode Cutover Procedure
# Agent 20 (Launch Readiness) — Phase 6
#
# IMPORTANT: This script documents the manual steps required.
# It does NOT auto-execute — review each step carefully.
# ============================================================

set -euo pipefail

echo "============================================================"
echo "  FormForge — Stripe Live Mode Cutover"
echo "============================================================"
echo ""
echo "This script guides you through switching from Stripe test"
echo "mode to live mode. Each step requires manual action."
echo ""
echo "Prerequisites:"
echo "  - Stripe account fully verified (identity + bank account)"
echo "  - All test-mode billing flows verified (Prompt 20.1)"
echo "  - Supabase Edge Functions deployed"
echo "  - Production frontend deployed to Vercel"
echo ""

# ============================================================
# STEP 1: Create Live Products & Prices in Stripe Dashboard
# ============================================================
echo "--- STEP 1: Create Live Products & Prices ---"
echo ""
echo "Go to: https://dashboard.stripe.com/products"
echo ""
echo "Create the following products with LIVE prices:"
echo ""
echo "  1. FormForge Pro"
echo "     - Monthly: \$29/mo  → note the price_xxx ID"
echo "     - Annual:  \$278/yr → note the price_xxx ID (= \$23/mo × 12, 20% off)"
echo ""
echo "  2. FormForge Growth"
echo "     - Monthly: \$59/mo  → note the price_xxx ID"
echo "     - Annual:  \$566/yr → note the price_xxx ID (= \$47/mo × 12, 20% off)"
echo ""
echo "  3. FormForge Business"
echo "     - Monthly: \$99/mo  → note the price_xxx ID"
echo "     - Annual:  \$950/yr → note the price_xxx ID (= \$79/mo × 12, 20% off)"
echo ""
echo "Record all 6 live price IDs below:"
echo ""
echo "  PRO_MONTHLY=price_xxx"
echo "  PRO_ANNUAL=price_xxx"
echo "  GROWTH_MONTHLY=price_xxx"
echo "  GROWTH_ANNUAL=price_xxx"
echo "  BUSINESS_MONTHLY=price_xxx"
echo "  BUSINESS_ANNUAL=price_xxx"
echo ""
read -p "Press Enter when all products/prices are created..."

# ============================================================
# STEP 2: Update src/lib/stripe.ts with Live Price IDs
# ============================================================
echo ""
echo "--- STEP 2: Update Price IDs in Code ---"
echo ""
echo "Edit: src/lib/stripe.ts"
echo ""
echo "Replace the placeholder price IDs in STRIPE_PLANS:"
echo ""
echo "  pro: {"
echo "    monthly: \"price_pro_monthly_placeholder\",   → \"\$PRO_MONTHLY\""
echo "    annual:  \"price_pro_annual_placeholder\",    → \"\$PRO_ANNUAL\""
echo "  }"
echo "  growth: {"
echo "    monthly: \"price_growth_monthly_placeholder\", → \"\$GROWTH_MONTHLY\""
echo "    annual:  \"price_growth_annual_placeholder\",  → \"\$GROWTH_ANNUAL\""
echo "  }"
echo "  business: {"
echo "    monthly: \"price_business_monthly_placeholder\", → \"\$BUSINESS_MONTHLY\""
echo "    annual:  \"price_business_annual_placeholder\",  → \"\$BUSINESS_ANNUAL\""
echo "  }"
echo ""
read -p "Press Enter when stripe.ts is updated..."

# ============================================================
# STEP 3: Update stripe-webhook Edge Function Price Map
# ============================================================
echo ""
echo "--- STEP 3: Update Edge Function Price Map ---"
echo ""
echo "Edit: supabase/functions/stripe-webhook/index.ts"
echo ""
echo "Update the priceMap in resolvePlanFromPrice():"
echo ""
echo "  const priceMap: Record<string, string> = {"
echo "    \"\$PRO_MONTHLY\":      \"pro\","
echo "    \"\$PRO_ANNUAL\":       \"pro\","
echo "    \"\$GROWTH_MONTHLY\":   \"growth\","
echo "    \"\$GROWTH_ANNUAL\":    \"growth\","
echo "    \"\$BUSINESS_MONTHLY\": \"business\","
echo "    \"\$BUSINESS_ANNUAL\":  \"business\","
echo "  };"
echo ""
read -p "Press Enter when edge function is updated..."

# ============================================================
# STEP 4: Get Live API Keys from Stripe Dashboard
# ============================================================
echo ""
echo "--- STEP 4: Get Live API Keys ---"
echo ""
echo "Go to: https://dashboard.stripe.com/apikeys"
echo ""
echo "Copy:"
echo "  - Publishable key: pk_live_xxx"
echo "  - Secret key: sk_live_xxx"
echo ""
echo "IMPORTANT: Never commit live keys to code."
echo "They go in environment variables only."
echo ""
read -p "Press Enter when you have both keys..."

# ============================================================
# STEP 5: Configure Live Webhook in Stripe Dashboard
# ============================================================
echo ""
echo "--- STEP 5: Configure Live Webhook ---"
echo ""
echo "Go to: https://dashboard.stripe.com/webhooks"
echo ""
echo "Create new endpoint:"
echo "  URL: https://rsuolemihuqjvrcpqjpa.supabase.co/functions/v1/stripe-webhook"
echo ""
echo "  Events to listen for:"
echo "    - checkout.session.completed"
echo "    - invoice.paid"
echo "    - invoice.payment_failed"
echo "    - customer.subscription.updated"
echo "    - customer.subscription.deleted"
echo ""
echo "Copy the Webhook signing secret: whsec_xxx"
echo ""
read -p "Press Enter when webhook is configured..."

# ============================================================
# STEP 6: Update Supabase Edge Function Secrets
# ============================================================
echo ""
echo "--- STEP 6: Update Supabase Secrets ---"
echo ""
echo "Run the following command with your live keys:"
echo ""
echo "  npx supabase secrets set \\"
echo "    STRIPE_SECRET_KEY=sk_live_xxx \\"
echo "    STRIPE_WEBHOOK_SECRET=whsec_xxx \\"
echo "    --project-ref rsuolemihuqjvrcpqjpa"
echo ""
read -p "Press Enter when secrets are set..."

# ============================================================
# STEP 7: Update Vercel Environment Variables
# ============================================================
echo ""
echo "--- STEP 7: Update Vercel Environment Variables ---"
echo ""
echo "Go to: Vercel Dashboard → Project Settings → Environment Variables"
echo ""
echo "Update:"
echo "  VITE_STRIPE_PUBLISHABLE_KEY = pk_live_xxx"
echo ""
echo "Ensure this is set for Production environment."
echo ""
read -p "Press Enter when Vercel env vars are updated..."

# ============================================================
# STEP 8: Deploy
# ============================================================
echo ""
echo "--- STEP 8: Deploy ---"
echo ""
echo "1. Redeploy stripe-webhook edge function:"
echo "   npx supabase functions deploy stripe-webhook --project-ref rsuolemihuqjvrcpqjpa"
echo ""
echo "2. Commit and push frontend changes (stripe.ts price IDs):"
echo "   git add src/lib/stripe.ts"
echo "   git commit -m 'Switch Stripe to live mode price IDs'"
echo "   git push"
echo ""
echo "3. Vercel will auto-deploy with new env vars on push."
echo ""
read -p "Press Enter when both are deployed..."

# ============================================================
# STEP 9: Verify Live Mode
# ============================================================
echo ""
echo "--- STEP 9: Verify Live Mode ---"
echo ""
echo "1. Open the app in production."
echo "2. Navigate to /pricing."
echo "3. Click 'Upgrade to Pro' (use your own card for a real \$29 charge)."
echo "4. Complete Stripe Checkout."
echo "5. Verify:"
echo "   - Redirected to /checkout/success"
echo "   - Stripe webhook fires (check Stripe Dashboard → Events)"
echo "   - Subscription record created in Supabase subscriptions table"
echo "   - useSubscription returns plan='pro'"
echo "   - usePlanLimits shows Pro limits"
echo "6. Open Billing Portal (Settings → Billing)."
echo "7. Cancel the test subscription."
echo "8. Verify subscription status changes to 'canceled' in DB."
echo ""
echo "If all checks pass: LIVE MODE IS ACTIVE."
echo ""

echo "============================================================"
echo "  Cutover Complete"
echo "============================================================"
echo ""
echo "BILLING DATA FLOW:"
echo ""
echo "  User clicks 'Upgrade' on /pricing"
echo "    → CheckoutButton calls supabase.functions.invoke('stripe-webhook'...)"
echo "    → Actually: creates Stripe Checkout session via Stripe.js"
echo "    → User completes payment on Stripe hosted page"
echo "    → Stripe fires webhook → stripe-webhook Edge Function"
echo "    → verifyStripeSignature() validates HMAC"
echo "    → resolvePlanFromPrice() maps price_id → plan tier"
echo "    → Upsert subscription record in DB"
echo "    → Supabase Realtime notifies useSubscription"
echo "    → useSubscription invalidates query"
echo "    → usePlanLimits recalculates limits"
echo "    → UI reflects new plan"
echo ""
echo "TROUBLESHOOTING:"
echo ""
echo "  Checkout doesn't redirect?"
echo "    → Check VITE_STRIPE_PUBLISHABLE_KEY matches live key"
echo "    → Check browser console for Stripe.js errors"
echo ""
echo "  Webhook not firing?"
echo "    → Check Stripe Dashboard → Webhooks → Recent deliveries"
echo "    → Verify endpoint URL is correct"
echo "    → Check edge function logs: npx supabase functions logs stripe-webhook"
echo ""
echo "  Subscription not created in DB?"
echo "    → Check STRIPE_WEBHOOK_SECRET matches the live webhook secret"
echo "    → Check stripe-webhook logs for Supabase insert errors"
echo "    → Verify RLS allows service role inserts"
echo ""
echo "  Plan not reflected in UI?"
echo "    → Check subscriptions table has correct workspace_id"
echo "    → Check Realtime is enabled on subscriptions table"
echo "    → Check useSubscription query key matches workspace"
echo ""
echo "ROLLBACK:"
echo ""
echo "  1. In Stripe Dashboard: disable/pause the live webhook"
echo "  2. In Vercel: revert VITE_STRIPE_PUBLISHABLE_KEY to test key"
echo "  3. In Supabase secrets: revert STRIPE_SECRET_KEY to test key"
echo "  4. Redeploy edge function and frontend"
echo "  5. Any live charges must be refunded manually in Stripe"
